version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/mwutil"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
