[project]
name = "mwutil"
version = "0.1.0"
description = "CLI tool that helps managing MediaWiki development environments"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argcomplete>=3.6.2",
    "hfilesize>=0.1.0",
    "pyperclip>=1.11.0",
    "python-dotenv>=1.1.1",
    "questionary>=2.1.1",
    "rich>=14.2.0",
    "watchdog>=6.0.0",
]
[project.scripts]
mwutil-py = "mwutil.cli:main"

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
