name: Lint code
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
jobs:
  lint-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Lint python code
        run: uv run -- ruff check
